name: 'Check modified files in directories'
description: "Check if there are modified files on a given directories."
inputs:
  directories:
    description: "The string with directories to walk through"
    required: true
    default: "config/ infra/ docs/" # example
outputs:
  matched: # id of the output
    description: 'True or false if files has been changed'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
   - ${{ inputs.directories }}
