name: 'Check modified files in directories'
description: "Check if there are modified files on a given directories."
author: 'Admir Trakic'
inputs:
  directories:
    description: "The string with directories and/or files to check"
    required: true
    default: ".github/workflows/ README.md Dockefile"
outputs:
  matched: # id of the output
    description: 'True or false if files has been changed'
runs:
  using: 'docker'
  #image: 'Dockerfile'
  #args:
  # - ${{ inputs.directories }}
  image: docker://ghcr.io/atrakic/check-modified-files-action:main
  env:
    INPUT_DIRECTORIES: ${{ inputs.directories }}
