name: ci

on: 
  pull_request:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        name: "Check container builds"
        with:
          directories: "docs/ examples/"

