name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2      
      - uses: ./
        name: "Check modified files"
        with:
          directories: "examples/ .github/workflows/ entrypoint.sh action.yml README.md Dockefile"
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        if: github.ref != 'refs/heads/main'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
