name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2      
      
      - uses: ./
        id: modified_files
        name: "Check modified files"
        with:
          directories: ".github/workflows/ entrypoint.sh action.yml README.md Dockefile"
      
      - name: Dump github context
        run: echo "$GITHUB_CONTEXT"
        if: steps.modified_files.outputs.matched == 'true'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
